name: Bug report
description: Report a problem in spec tooling, iOS, Android, or registry charts
title: "[bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue. Include enough detail to reproduce and triage quickly.
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Where is the issue?
      options:
        - spec
        - iOS SwiftUI
        - Android Compose
        - registry chart
        - CI/release
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A short description of the issue.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction
      description: List exact steps and inputs used.
      placeholder: |
        1. Run ...
        2. Open ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or stack trace
      render: shell
  - type: input
    id: spec_version
    attributes:
      label: ChartSpec version
      description: Version in your JSON (for example 1.1.0)
